# <center>PR 5</center>
# <center>Calculative Foundation</center>

In [38]:
import numpy as np
from scipy.linalg import lu
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

#### Part A: Vector & Matrix Fundamentals

In [13]:
data = np.array([
    [85, 90, 88, 92],
    [60, 55, 65, 70],
    [95, 85, 92, 88],
    [45, 50, 40, 55],
    [78, 80, 85, 82]
])
data

array([[85, 90, 88, 92],
       [60, 55, 65, 70],
       [95, 85, 92, 88],
       [45, 50, 40, 55],
       [78, 80, 85, 82]])

In [14]:
s1 = data[0]
s2 = data[1]

In [15]:
norm1_s1 = np.linalg.norm(s1, ord=1)
norm2_s1 = np.linalg.norm(s1, ord=2)

In [17]:
dot_product = np.dot(s1, s2)

In [18]:
cos_theta = dot_product / (np.linalg.norm(s1) * np.linalg.norm(s2))
angle_deg = np.degrees(np.arccos(cos_theta))

In [21]:
s1_3d = s1[:3]
s2_3d = s2[:3]
cross_product = np.cross(s1_3d, s2_3d)

In [25]:
projection_s1_s2 = (np.dot(s1, s2) / np.dot(s2, s2)) * s2

In [26]:
print(f"Norm-1 of Student 1: {norm1_s1}")
print(f"Norm-2 of Student 1: {norm2_s1:.2f}")
print(f"Dot Product (Student 1 & 2): {dot_product}")
print(f"Angle between Student 1 & 2: {angle_deg:.2f} degrees")
print(f"Cross Product (First 3 subjects): {cross_product}")
print(f"Projection of Student 1 onto Student 2: {projection_s1_s2}")

Norm-1 of Student 1: 355.0
Norm-2 of Student 1: 177.58
Dot Product (Student 1 & 2): 22210
Angle between Student 1 & 2: 4.72 degrees
Cross Product (First 3 subjects): [1010 -245 -725]
Projection of Student 1 onto Student 2: [84.60952381 77.55873016 91.66031746 98.71111111]


#### Part B: Matrix Operations

In [27]:
A = data
B = data + 5

In [30]:
matrix_addition = A + B

matrix_multiplication = np.dot(A.T, A)

matrix_transpose = A.T

matrix_inverse = np.linalg.inv(matrix_multiplication)
matrix_determinant = np.linalg.det(matrix_multiplication)

In [31]:
print("Matrix Transpose:\n", matrix_transpose)
print("Determinant of A.T * A:", matrix_determinant)


Matrix Transpose:
 [[85 60 95 45 78]
 [90 55 85 50 80]
 [88 65 92 40 85]
 [92 70 88 55 82]]
Determinant of A.T * A: 70370307499.99829


#### Part C: Linear Transformations & Geometry

###### A line (1D) connects two data points (students), while a plane (2D) is a flat surface that can connect multiple points.

###### A hyperplane is simply a geometric boundary used to divide data, and it always has exactly one dimension less than your total dataset space.

###### As dimensions increase with more subjects, the divider scales up: a 1D line divides a 2D space, a 2D plane divides a 3D space, and a 3D hyperplane divides a 4D space.

#### Part D: Eigenvalues & Decomposition

In [43]:
cov_matrix = np.cov(A)
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

P, L, U = lu(A)

U_svd, S_svd, Vt_svd = np.linalg.svd(A)


In [35]:
print("Eigenvalues:\n", eigenvalues)
print("\nLU Decomposition (L Matrix):\n", L)
print("\nSVD (Singular Values):\n", S_svd)


Eigenvalues:
 [ 6.11020935e+01  1.46295643e+01  4.47683422e+01 -2.53522594e-15
 -1.63512067e-15]

LU Decomposition (L Matrix):
 [[ 1.          0.          0.          0.        ]
 [ 0.89473684  1.          0.          0.        ]
 [ 0.47368421  0.69811321  1.          0.        ]
 [ 0.63157895  0.09433962 -0.8425      1.        ]
 [ 0.82105263  0.73207547 -0.7025      0.17407687]]

SVD (Singular Values):
 [339.1556417   13.15180936   8.97759417   6.62445576]


#### Part E: Dimensionality Reduction

In [41]:
pca = PCA(n_components=2)
A_pca = pca.fit_transform(A)

student_averages = np.mean(A, axis=1)
overall_mean = np.mean(student_averages)
labels = np.where(student_averages >= overall_mean, "Above Average", "Below Average")

lda = LDA(n_components=1)

A_lda = lda.fit_transform(A, labels)


In [42]:
print("PCA:\n", A_pca)
print("\nDummy Classification Labels:\n", labels)
print("\nLDA Transformation:\n", A_lda)

PCA:
 [[ 2.90492899e+01  5.80437197e+00]
 [-2.29260270e+01 -6.88431413e+00]
 [ 3.26887383e+01 -3.12747451e+00]
 [-5.36612058e+01  4.18456771e+00]
 [ 1.48492046e+01  2.28489599e-02]]

Dummy Classification Labels:
 ['Above Average' 'Below Average' 'Above Average' 'Below Average'
 'Above Average']

LDA Transformation:
 [[-3.68594059]
 [ 3.74102393]
 [-2.95944455]
 [ 4.24964952]
 [-1.34528831]]
